package org.example.opp_cw.model;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.Data;
import org.example.opp_cw.annotation.IsValueNull;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

import java.util.List;

@Document
@Data
public class Credentials {
    @NotNull
    @Pattern(regexp = "^[a-zA-Z0-9@_*.]+$", message = "invalid username")
    @Size(min = 8)
    private String username;
    @NotNull
    @Pattern(regexp = "^[a-zA-Z0-9@_*.]+$", message = "invalid password")
    @Size(min = 8)
    private String password;
    @IsValueNull(message = "back up codes must be null. They are generated by the system")
    private List<Integer> backUpCodes;

    public void setPassword(@NotNull @Pattern(regexp = "^[a-zA-Z0-9@_*.]+$", message = "invalid password") @Size(min = 8) String password) {
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder(16);
        this.password = encoder.encode(password);
    }
}
