package org.example.opp_cw.model;

import jakarta.validation.Valid;
import lombok.Data;
import org.example.opp_cw.annotation.IsObjectIdValid;
import org.example.opp_cw.annotation.IsValueNull;
import org.example.opp_cw.dto.RandomSecureCode;
import org.example.opp_cw.dto.userdetails.Password;
import org.example.opp_cw.dto.userdetails.UserName;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.FieldType;
import org.springframework.data.mongodb.core.mapping.MongoId;

import java.util.List;

@Document
@Data
public class Credentials {
    @MongoId(FieldType.STRING)
    private String id;
    @IsObjectIdValid
    private String ownerId;
    @Valid
    private UserName userName;
    @Valid
    private Password password;

    @IsValueNull(message = "back up codes must be null. They are generated by the system")
    private List<RandomSecureCode> backUpCodes;
}
