spring:
  application:
    name: OOP_CW
  data:
    mongodb:
      customer:
        uri: mongodb://localhost:27017/customer_db
      admin:
        uri: mongodb://localhost:27017/admin_db

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

server:
  port: 8080