package org.backend.enums;

public enum EventTypes {
    QUE_TICKET, BUY_TICKET, ADD_TICKET, REMOVE_TICKET, ADD_THREAD, START_THREAD, REMOVED_THREAD, ADD_TICKET_FAILED, REMOVE_PURCHASE_FAILED, REMOVE_PURCHASE, QUE_TICKET_FAILED, BUY_TICKET_FAILED, REMOVE_TICKET_FAILED, CLEAR_MEM
}
